### ISSUE TITLE
Too good

### ISSUE THREAD

**Issue by MSandeep96** [aayushgupta1/Django-user-auth#1]
This project is :fire:. How to cool this down?

**Comment by aayushgupta1** [comment]
Want to help? We can fire it up even more.

**Comment by MSandeep96** [comment]
If you're willing to move to Node.js then yes

**Comment by aayushgupta1** [comment]
:sad:

**Comment by aayushgupta1** [comment]
We can try using using your expertise in this.

**Comment by aayushgupta1** [comment]
We can try using using your expertise in this.
